import { Role } from '../../../common/enums/role.enum';

const all = ['*'];

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  [Role.SUPER_ADMIN]: all,
  [Role.CHAIRMAN]: all,
  [Role.SECRETARY]: [
    'residents:read',
    'residents:write',
    'complaints:read',
    'complaints:write',
    'complaints:update',
    'finance:read',
    'finance:write',
    'meetings:write',
    'meetings:vote',
    'security:write',
    'security:preapprove',
    'documents:request',
    'documents:approve',
    'dashboard:resident',
    'amenities:book',
    'parking:assign',
    'parking:violation',
  ],
  [Role.TREASURER]: [
    'finance:read',
    'finance:write',
    'finance:approve',
    'meetings:vote',
    'security:preapprove',
    'documents:request',
    'dashboard:treasurer',
    'dashboard:resident',
    'amenities:book',
    'parking:violation',
  ],
  [Role.JOINT_SECRETARY]: [
    'residents:read',
    'residents:write',
    'complaints:write',
    'complaints:update',
    'meetings:write',
    'meetings:vote',
    'security:preapprove',
    'documents:request',
    'documents:approve',
    'dashboard:resident',
    'amenities:book',
    'parking:assign',
    'parking:violation',
  ],
  [Role.COMMITTEE_MEMBER]: [
    'residents:read',
    'complaints:read',
    'complaints:write',
    'meetings:vote',
    'security:preapprove',
    'documents:request',
    'dashboard:resident',
    'amenities:book',
    'parking:violation',
  ],
  [Role.TOWER_CAPTAIN]: [
    'tower:read',
    'tower:write',
    'complaints:write',
    'complaints:read',
    'meetings:write',
    'meetings:vote',
    'security:preapprove',
    'documents:request',
    'dashboard:resident',
    'amenities:book',
    'parking:violation',
  ],
  [Role.ACCOUNTANT]: ['finance:read', 'finance:write'],
  [Role.FACILITY_MANAGER]: ['amenities:read', 'amenities:write', 'vendors:read'],
  [Role.SECURITY_SUPERVISOR]: ['security:read', 'security:write', 'parking:violation'],
  [Role.SECURITY_GUARD]: ['security:write', 'parking:violation'],
  [Role.MAINTENANCE_STAFF]: ['complaints:update'],
  [Role.OWNER_RESIDENT]: [
    'resident:self',
    'complaints:write',
    'complaints:read',
    'payments:write',
    'meetings:vote',
    'security:preapprove',
    'documents:request',
    'dashboard:resident',
    'amenities:book',
    'parking:violation',
  ],
  [Role.OWNER_NONRESIDENT]: [
    'resident:self',
    'tenant:approve',
    'complaints:write',
    'complaints:read',
    'meetings:vote',
    'security:preapprove',
    'documents:request',
    'dashboard:resident',
    'amenities:book',
    'parking:violation',
  ],
  [Role.TENANT]: [
    'resident:self',
    'complaints:write',
    'complaints:read',
    'meetings:vote',
    'security:preapprove',
    'documents:request',
    'amenities:book',
    'parking:violation',
  ],
  [Role.FAMILY_MEMBER]: [
    'resident:view',
    'complaints:write',
    'complaints:read',
    'meetings:vote',
    'security:preapprove',
    'documents:request',
    'dashboard:resident',
    'amenities:book',
    'parking:violation',
  ],
};
